In [1]:
##### This code is from Updated Testing Reddit - No Con- bias (Fictitious Play)-01092022
##### This code replace the big real datanetwork with small sythetic network
import scipy
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from itertools import combinations
import time
import random
from scipy.stats import beta
import pandas as pd
import copy
%matplotlib inline
# %run Check_Derivation_of_Two_Opinions.ipynb
#%run pure_strategy_selection.ipynb  #include simple selection algorithm
import scipy.io
import collections
import sys
from itertools import count
from itertools import combinations
from itertools import product
import scipy.optimize
import csv
import os.path

# add parent directory to path so that utils is available
sys.path.append('..')
from utils import *

from game import *

# Game Parameters
game_rounds = 5
memory = 50
k = 2

current_path = os.getcwd()

# Create the 'results' directory if it doesn't exist
os.makedirs('results', exist_ok=True)

np.set_printoptions(precision=5)

calculate_polarization = calculate_polarization1

    # Fixed initial condition + memeory = 50

## Mathmatic Functions

### 1. Import Network

In [2]:
# Import Synthetic Network Data
df = pd.read_csv(f'{current_path}/data/Adjacency Matrix.csv', header=None)
G = np.array(df[df.columns[:]])
# print(G)
df1 = pd.read_csv(f'{current_path}/data/Innate Opinion.csv', header=None)
s = np.array(df1[df1.columns[:]])
# print(G.shape)

# Set n according to the data
n = len(s[:])
# print(n)

In [3]:
# # Doesn't work with network_anl

# Import Synthetic Network Data
df = pd.read_csv(f'{current_path}/data/5Adj_matrix.csv', header=None)
G = np.array(df[df.columns[:]])
# # # print(G)
df1 = pd.read_csv(f'{current_path}/data/5innate_op.csv', header=None)
s = np.array(df1[df1.columns[:]])

# print(s)
# print(G.shape)

# # Set n according to the data
n = len(s[:])
# # print(n)

In [4]:
################## Process the Network Data
L = scipy.sparse.csgraph.laplacian(G, normed=False)  # Return the Laplacian matrix
A = np.linalg.inv(np.identity(n) + L)  # A = (I + L)^(-1)\n  Stanford paper theory
m = num_edges(L, n)                    # call the function to calculate the number of edges
# what the twitter graph looks like
nxG = nx.from_numpy_array(G)
#plt.figure(figsize=(20, 20))
# nx.draw(nxG)
columnsum_ij = np.sum(A, axis=0)
# print(columnsum_ij)

In [5]:
def network_anl2(s,n,G,agent):
    print(str(agent)+' opinion: ' + str(s[agent]))
    print(str(agent)+' neighbors: '+ str(np.nonzero(G[agent])))

    s_aa = s[:, 0]
    my_dict = {index: value for index, value in enumerate(s_aa)}
    sorting_s = sorted(my_dict.items(), key=lambda x:x[1])
    sorted_S = dict(sorting_s)

    temp = list(sorted_S.items())
    res = [idx for idx, key in enumerate(temp) if key[0]==agent]
    # printing result
    print("Opinion rank of this agent is : " + str(res))



    #print("___________________Max Analyze__________________________________________")
    nxG = nx.from_numpy_array(G)
    # G = nx.karate_club_graph()
    print("_______________Degree Centrality___________________")
    deg_centrality = nx.degree_centrality(nxG)
    sortedDict = sorted(deg_centrality.items(), key=lambda x:x[1])
    converted_dict = dict(sortedDict)
    temp1 = list(converted_dict.items())
    res1 = [idx for idx, key in enumerate(temp1) if key[0]==agent]
    print("rank of this agent is : " + str(res1))
    print(converted_dict[agent])

    # print(converted_dict)
    print("                           ")
    print("_______________Closeness Rank________________________")
    close_centrality = nx.closeness_centrality(nxG)
    sortedDict1 = sorted(close_centrality.items(), key=lambda x:x[1])
    converted_dict1 = dict(sortedDict1)
    temp2 = list(converted_dict1.items())
    res2 = [idx for idx, key in enumerate(temp2) if key[0]==agent]
    print("rank of this agent is : " + str(res2))
    print(converted_dict1[agent])
    # print(converted_dict1)
    print("                           ")
    print("_______________Page Rank_____________________________")
    pr = nx.eigenvector_centrality(nxG)
    sortedDict3 = sorted(pr.items(), key=lambda x:x[1])
    converted_dict3 = dict(sortedDict3)
    temp3 = list(converted_dict3.items())
    res3 = [idx for idx, key in enumerate(temp3) if key[0]==agent]
    print("rank of this agent is : " + str(res3))
    print(converted_dict3[agent])
    # print(converted_dict3)

    print("                           ")

    def gap(op, n):
        ones = np.ones((n, 1))
        x = op - (np.dot(np.transpose(op),ones)/n) * ones
        return abs(x)

    gap = gap(s,n)
    my_gap = {index: value for index, value in enumerate(gap)}
    sorting_gap = sorted(my_gap.items(), key=lambda x:x[1])
    sorted_gap = dict(sorting_gap)
    #print(sorted_gap)
    temp4 = list(sorted_gap.items())
    res4 = [idx for idx, key in enumerate(temp4) if key[0]==agent]
    print("Agent's opinion gap to mean opinion is ranked as: " + str(res4))


    print("___________________Max Analyze__________________________________________")
nxG = nx.from_numpy_array(G)
# G = nx.karate_club_graph()
print("_______________Degree Centrality_____________________________")
plt.figure(figsize =(15, 15))
deg_centrality = nx.degree_centrality(nxG)
sortedDict = sorted(deg_centrality.items(), key=lambda x:x[1])
converted_dict = dict(sortedDict)
print(converted_dict)
print("                           ")
print("_______________Closeness Rank_____________________________")
close_centrality = nx.closeness_centrality(nxG)
sortedDict1 = sorted(close_centrality.items(), key=lambda x:x[1])
converted_dict1 = dict(sortedDict1)
print(converted_dict1)
print("                           ")
print("_______________Page Rank_____________________________")
pr = nx.eigenvector_centrality(nxG)
sortedDict3 = sorted(pr.items(), key=lambda x:x[1])
converted_dict3 = dict(sortedDict3)
print(converted_dict3)

print("                           ")

def gap(op, n):
    ones = np.ones((n, 1))
    x = op - (np.dot(np.transpose(op),ones)/n) * ones
    return abs(x)

gap = gap(s,n)
my_gap = {index: value for index, value in enumerate(gap)}
sorting_gap = sorted(my_gap.items(), key=lambda x:x[1])
sorted_gap = dict(sorting_gap)
print(sorted_gap)




_______________Degree Centrality_____________________________
{4: 0.25, 0: 0.75, 1: 0.75, 2: 0.75, 3: 1.0}
                           
_______________Closeness Rank_____________________________
{4: 0.5714285714285714, 0: 0.8, 1: 0.8, 2: 0.8, 3: 1.0}
                           
_______________Page Rank_____________________________
{4: 0.16965100981173117, 0: 0.4820442559301269, 1: 0.4820442559301269, 2: 0.4820442559301269, 3: 0.5235633112090369}
                           
{0: array([0.19703]), 3: array([0.21003]), 2: array([0.21351]), 4: array([0.26584]), 1: array([0.45939])}


<Figure size 1500x1500 with 0 Axes>

In [6]:
# # TODO resolve network_anl (from this file) and network_anl2 (from utils) produce different results
# agent = 6
# # network_anl(s,n,G,agent)
# print('_' * 10)
# network_anl2(s,n,G,agent)

### 2. Equilibrium & Polarization 
$$P(z) = z ^T * z $$


In [7]:
calculate_polarization1(s, n, A, L)

Innate_polarization:	0.41022891110361115
Equi_polarization:	0.04411213470472514
Difference:		-0.366116776398886


## 5. Innate Op and Game

# Fictitious Play Start !


In [8]:
def save_(result: GameResult, k: int, experiment: int):
    pd.DataFrame(result.payoff_matrix).to_csv(
        f'results/Payoff-Matrix-k-{k}-experiment-{experiment}.csv')

    # Save the original standard output
    original_stdout = sys.stdout

    with open(f'results/Result-k-{k}-experiment-{experiment}.txt', "w") as f:
        # Change the standard output to the file we created.
        sys.stdout = f

        print('Initial Condition - (agent, opinion, pol)')
        # print(f'Innate op {s}')
        # print(f'Adjacency matrix {G}')
        # print('Selected Nodeset, k_Opinions, Steady-state polarization')
        print(f'Max:{result.first_max}')
        print(f'Min{result.first_min}')

        print('_____________________')
        print(f'Max Pol: {result.equi_max} Min Pol: {result.equi_min}')
        # MAXimizer's distribution of LAST 100 iteration
        print('Max_distribution_last_100')
        max_l100_fre = result.max_history_last_100/100
        print(max_l100_fre[np.nonzero(max_l100_fre)])
        # print for small network
        # print(max_history_last_100)
        # # Print for Large Network
        print(np.nonzero(max_l100_fre))

        print('Max_distribution_all')
        max_fre = result.max_history/result.game_rounds
        print(max_fre[np.nonzero(max_fre)])
        print([np.nonzero(max_fre)])

        # MINimizer's Strategy in the last 100 round
        counter = collections.Counter(result.min_touched_last_100)
        # frequency of all min options in order
        fla_min_fre = np.array(list(counter.values()))/(100)
        print('Min_distribution_last_100')
        print(fla_min_fre)
        print(counter)
        # print(min_touched_last_100)

        # a dictionary include {'min_option': count of this choice}
        counter_1 = collections.Counter(result.min_touched_all)
        # frequency of all min options in order
        fla_min_fre_1 = np.array(list(counter_1.values()))/result.game_rounds
        print('Min_distribution_all')
        print(fla_min_fre_1)
        print(counter_1)
        np.set_printoptions(precision=3)

        # a dictionary include {'min_option': count of this choice}
        counter_a = collections.Counter(result.min_history)
        print(counter_a)

        print(f'min_recent_{memory}_touched')  # then stop at Game 202
        print(result.min_touched)
        print(f'max_recent_{memory}_touched')
        print(result.max_touched)

        # Reset the standard output to its original value
        sys.stdout = original_stdout

In [9]:
game = Game(s, A, L, k)
result = game.run(game_rounds, memory)

Nodes, opinions
[2, 4] (1, 1)
Nodes, opinions
[0, 3] (0.5, 0.5)
min_history [((0, 3), (0.5, 0.5))]
--------------------
Game 1
----------
min_history [((0, 3), (0.5, 0.5))]
max_history [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0]
fla_min_fre [1.]
Max_por 0.09181344162282333
Max_por 0.10085992937712412
Max_por 0.1244223977280837
all_por [0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.00916 0.0416
 0.0416  0.09181 0.      0.      0.      0.      0.03724 0.08109 0.10086
 0.02249 0.      0.      0.      0.      0.05643 0.07023 0.12442 0.016
 0.      0.      0.      0.     ]
column - best action: 34
Maximizer found its target 2 agent: [2, 4] op: (1, 0)
fre_max at spot 0.5
M
[[-0.02392 -0.02392  0.17608 -0.00431 -0.12392]]
M
[[-0.14059 -0.14059  0.05941 -0.03764  0.25941]]
champion:  [0, 1] [0.39593 0.39593] 0.06153260863178252
M
[[-0.03145  0.14597  0.16855 -0.0629  -0.22016]

In [10]:
experiment = 1
save_(result, k, experiment)